# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afe8f434e7581138ba53ebb2518ca997845140000300d296ecd3cb1e1d274cc1f80ff3cef8637d7971c2d42658c33448476acce5f538c782e6afb210a9d023bf

test:
  secret_key_base: 5ae92ebe653bbdc169966732db270c8369248c013a55714e528648d86d1c7daef7b3985f7a32b67c470a593530cca540af0ea39ad7b531fcc1cc961ff8b041ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
